### ISSUE TITLE
Separation of concerns 

### ISSUE THREAD

**Issue by jewpaltz** [Ansykut/CPS493FinalProject#1]
https://github.com/Ansykut/CPS493FinalProject/blob/ce998b18b53cfa50eba7ac139682f1ed83cc3978/client/src/views/MyActivityView.vue#L125

I hope that you are working on centralizing all of this and moving the Model info into their own files

**Comment by Ansykut** [comment]
Thanks for the advice, was able to implement this afternoon! actually issues I was having. Thanks!!!
